name: flutter_test_app

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  http: ^0.13.6
  slack_notifier: ^1.3.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/
  - assets/fonts/

  fonts:
    - family: IBMPlexSansJP
      fonts:
        - asset: assets/fonts/IBMPlexSansJP-Thin.ttf  
          weight: 100
        - asset: assets/fonts/IBMPlexSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansJP-Bold.ttf
          weight: 700
    - family: Mukta
      fonts:
        # - asset: assets/fonts/Mukta-Thin.ttf  
        #   weight: 100
        - asset: assets/fonts/Mukta-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mukta-Light.ttf
          weight: 300
        - asset: assets/fonts/Mukta-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mukta-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mukta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700